version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

volumes:
  db: